const actions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_BOARDS: 'SET_BOARDS',
  ADD_SINGLE_BOARD: 'ADD_SINGLE_BOARD',
  REMOVE_SINGLE_BOARD: 'REMOVE_SINGLE_BOARD',
  UPDATE_SINGLE_BOARD: 'UPDATE_SINGLE_BOARD',
  SET_CURRENT_BOARD: 'SET_CURRENT_BOARD',
  SET_COLUMNS: 'SET_COLUMNS',
  SET_CURRENT_COLUMN: 'SET_CURRENT_COLUMN',
  SET_LABELS: 'SET_LABELS',
  SET_MEMBERS: 'SET_MEMEBERS',
  SET_CARDS: 'SET_CARDS',
  SET_CURRENT_CARD: 'SET_CURRENT_CARD',
  SAVE_ATTACHMENT: 'SAVE_ATTACHMENT',
}

export default actions;